name: PR-workflow

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        uses: zbeekman/ShellCheck-Linter-Action@v1.0.1
 
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run tests
        run: ./tests/test_runner
        shell: bash
    needs: lint 